version: "3.8"

services:
  # --- BASE DE DATOS ---
  db:
    build:
      context: ./App/database
    image: mariadb_projecto1
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: talent_connect_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - talent_network

  # --- CORREO (MAILHOG) ---
  mailhog:
    build:
      context: ./App/mail
    container_name: mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP Port
    networks:
      - talent_network

  # --- APP (CORE) ---
  app:
    build:
      context: ./App
      dockerfile: core/dockerfile
    image: talentconnect_app
    container_name: app
    volumes:
      - ./App:/var/www/html/
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_NAME: talent_connect_db
      DB_USER: user
      DB_PASS: 1234
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    depends_on:
      - db
      - mailhog
    networks:
      - talent_network

volumes:
  db-data:

networks:
  talent_network:
    driver: bridge
